// Mutations
export const ADD_COMPONENT_TO_COMPONENT_MAP = 'ADD_COMPONENT_TO_COMPONENT_MAP'
export const SET_SELECTED_ELEMENT_LIST = 'SET_SELECTED_ELEMENT_LIST'
export const ADD_TO_SELECTED_ELEMENT_LIST = 'ADD_TO_SELECTED_ELEMENT_LIST'
export const ADD_TO_COMPONENT_HTML_LIST = 'ADD_TO_COMPONENT_HTML_LIST'
export const SET_CLICKED_ELEMENT_LIST = 'SET_CLICKED_ELEMENT_LIST'
export const DELETE_ACTIVE_COMPONENT = 'DELETE_ACTIVE_COMPONENT'
export const SET_COMPONENT_MAP = 'SET_COMPONENT_MAP'
export const DELETE_FROM_QUEUE = 'DELETE_FROM_QUEUE'
export const DELETE_SELECTED_ELEMENT = 'DELETE_SELECTED_ELEMENT'
export const SET_STATE = 'SET_STATE'
export const ADD_PROJECT = 'ADD_PROJECT'
export const DELETE_FROM_COMPONENT_HTML_LIST =
  'DELETE_FROM_COMPONENT_HTML_LIST'
export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB'
export const ADD_COMPONENT_TO_ACTIVE_ROUTE_IN_ROUTE_MAP =
  'ADD_COMPONENT_TO_ACTIVE_ROUTE_IN_ROUTE_MAP'
export const ADD_ROUTE = 'ADD_ROUTE'
export const SET_ACTIVE_COMPONENT = 'SET_ACTIVE_COMPONENT'
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT'
export const SET_ACTIVE_ROUTE = 'SET_ACTIVE_ROUTE'
export const INCREMENT_PROJECT_ID = 'INCREMENT_PROJECT_ID'
export const SET_ROUTES = 'SET_ROUTES'
export const SET_COMPONENT_HTML_LIST = 'SET_COMPONENT_HTML_LIST'
export const SET_ACTIVE_ROUTE_ARRAY = 'SET_ACTIVE_ROUTE_ARRAY'
export const ADD_COMPONENT_TO_ACTIVE_ROUTE_CHILDREN =
  'ADD_COMPONENT_TO_ACTIVE_ROUTE_CHILDREN'
export const ADD_ROUTE_TO_COMPONENT_MAP = 'ADD_ROUTE_TO_COMPONENT_MAP'
export const DELETE_PROJECT_TAB = 'DELETE_PROJECT_TAB'
export const UPDATE_COMPONENT_CHILDREN_MULTISELECT_VALUE =
  'UPDATE_COMPONENT_CHILDREN_MULTISELECT_VALUE'
export const UPDATE_COMPONENT_NAME_INPUT_VALUE =
  'UPDATE_COMPONENT_NAME_INPUT_VALUE'
export const UPDATE_COMPONENT_CHILDREN_VALUE =
  'UPDATE_COMPONENT_CHILDREN_VALUE'
export const UPDATE_ACTIVE_COMPONENT_CHILDREN_VALUE =
  'UPDATE_ACTIVE_COMPONENT_CHILDREN_VALUE'
export const ADD_COMPONENT_TO_COMPONENT_CHILDREN =
  'ADD_COMPONENT_TO_COMPONENT_CHILDREN'
export const UPDATE_OPEN_MODAL = 'UPDATE_OPEN_MODAL'
export const PARENT_SELECTED = 'PARENT_SELECTED'
export const DELETE_ROUTE = 'DELETE_ROUTE'
export const DELETE_COMPONENT = 'DELETE_COMPONENT'
export const DELETE_USER_ACTIONS = 'DELETE_USER_ACTIONS'
export const REMOVE_ACTION_FROM_COMPONENT = 'REMOVE_ACTION_FROM_COMPONENT'
export const ADD_TO_COMPONENT_ACTIONS = 'ADD_TO_COMPONENT_ACTIONS'
export const ADD_TO_COMPONENT_STATE = 'ADD_TO_COMPONENT_STATE'
export const ADD_USER_ACTION = 'ADD_USER_ACTION'
export const ADD_TO_USER_STORE = 'ADD_TO_USER_STORE'

// Actions
export const registerComponent = 'registerComponent'
export const setSelectedElementList = 'setSelectedElementList'
export const addToSelectedElementList = 'addToSelectedElementList'
export const addToComponentElementList = 'addToComponentElementList'
export const setClickedElementList = 'setClickedElementList'
export const deleteActiveComponent = 'deleteActiveComponent'
export const setComponentMap = 'setComponentMap'
export const deleteFromQueue = 'deleteFromQueue'
export const deleteSelectedElement = 'deleteSelectedElement'
export const setState = 'setState'
export const addProject = 'addProject'
export const deleteFromComponentHtmlList = 'deleteFromComponentHtmlList'
export const changeActiveTab = 'changeActiveTab'
export const addRouteToRouteMap = 'addRouteToRouteMap'
export const setActiveComponent = 'setActiveComponent'
export const setActiveRoute = 'setActiveRoute'
export const incrementProjectId = 'incrementProjectId'
export const setRoutes = 'setRoutes'
export const setComponentHtmlList = 'setComponentHtmlList'
export const deleteProjectTab = 'deleteProjectTab'
// ChildrenMultiselect actions
export const updateComponentChildrenMultiselectValue =
  'updateComponentChildrenMultiselectValue'
export const updateActiveComponentChildrenValue =
  'updateActiveComponentChildrenValue'

export const updateComponentChildrenValue = 'updateComponentChildrenValue'
export const updateComponentNameInputValue = 'updateComponentNameInputValue'
export const updateOpenModal = 'updateOpenModal'
export const parentSelected = 'parentSelected'
export const deleteRoute = 'deleteRoute'
export const deleteComponent = 'deleteComponent'

export const deleteUserActions = 'deleteUserActions'
export const removeActionFromComponent = 'removeActionFromComponent'
export const addUserAction = 'addUserAction'
export const addToUserStore = 'addToUserStore'
