const htmlElementMap = {
  div: ['<div>', '</div>'],
  button: ['<button>', '</button>'],
  form: ['<form>', '</form>'],
  img: ['<img>', ''],
  link: ['<a href="#"/>', ''],
  list: ['<li>', '</li>'],
  paragraph: ['<p>', '</p>'],
  'list-ol': ['<ol>', '</ol>'],
  'list-ul': ['<ul>', '</ul>'],
  input: ['<input />', ''],
  navbar: ['<nav>', '</nav>'],
  header:['<header>', '</header>'],
  footer:['<footer>', '</footer>'],
  meta: ['<meta>', '</meta>'],
  h1:['<h1>', '</h1>'],
  h2:['<h2>', '</h2>'],
  h3:['<h3>', '</h3>'],
  h4:['<h4>', '</h4>'],
  h5:['<h5>', '</h5>'],
  h6:['<h6>', '</h6>'],
  'e-button':["<el-button", "</el-button>"],
  'e-input':["<el-input", "</el-input>"],
  'e-link':["<el-link", "</el-link>"],
  'e-form': ["<el-form", "</el-form>"],
  'e-checkbox': ["<el-checkbox", "</el-checkbox>"],
  'e-checkbox-button': ["<el-checkbox-button", "</el-checkbox-button>"],
  'e-date-picker': ["<el-date-picker", "</el-date-picker>"],
  'e-slider':["<el-slider", "</el-slider>"],
}

export default htmlElementMap
